"""add_seoman_v2_fields_and_models

Revision ID: 4daa20b0a073
Revises: 001
Create Date: 2026-01-07 16:42:09.348766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4daa20b0a073'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl_pages', sa.Column('load_time_ms', sa.Integer(), nullable=True))
    op.add_column('crawl_pages', sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('crawl_pages', sa.Column('raw_html_path', sa.Text(), nullable=True))
    op.add_column('crawl_pages', sa.Column('markdown_path', sa.Text(), nullable=True))
    op.add_column('crawl_pages', sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('crawl_pages', sa.Column('open_graph', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('crawl_pages', sa.Column('hreflang', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('crawl_pages', sa.Column('twitter_cards', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('crawl_pages', sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('crawl_pages', sa.Column('scripts_count', sa.Integer(), nullable=True))
    op.add_column('crawl_pages', sa.Column('stylesheets_count', sa.Integer(), nullable=True))
    op.add_column('crawl_pages', sa.Column('text_content_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawl_pages', 'text_content_hash')
    op.drop_column('crawl_pages', 'stylesheets_count')
    op.drop_column('crawl_pages', 'scripts_count')
    op.drop_column('crawl_pages', 'images')
    op.drop_column('crawl_pages', 'twitter_cards')
    op.drop_column('crawl_pages', 'hreflang')
    op.drop_column('crawl_pages', 'open_graph')
    op.drop_column('crawl_pages', 'structured_data')
    op.drop_column('crawl_pages', 'markdown_path')
    op.drop_column('crawl_pages', 'raw_html_path')
    op.drop_column('crawl_pages', 'issues')
    op.drop_column('crawl_pages', 'load_time_ms')
    # ### end Alembic commands ###
