"""add_recommendation_to_seo_audit_checks

Revision ID: 5afe231c7b22
Revises: 4daa20b0a073
Create Date: 2026-01-07 17:29:07.285851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5afe231c7b22'
down_revision: Union[str, None] = '4daa20b0a073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seo_audit_checks', sa.Column('recommendation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seo_audit_checks', 'recommendation')
    # ### end Alembic commands ###
