"""
Report-related schemas for PDF generation and report management.
"""

from typing import Optional
from pydantic import BaseModel, Field


class PDFOptions(BaseModel):
    """Options for PDF report generation."""

    include_code_examples: bool = Field(
        default=True,
        description="Include code fix examples in the report",
    )
    include_affected_urls: bool = Field(
        default=True,
        description="Include list of affected URLs per issue",
    )
    max_urls_per_issue: int = Field(
        default=10,
        ge=1,
        le=50,
        description="Maximum number of affected URLs to show per issue",
    )
    logo_url: Optional[str] = Field(
        default=None,
        description="URL to custom logo for white-labeling",
    )
    brand_color: str = Field(
        default="#2563eb",
        pattern=r"^#[0-9a-fA-F]{6}$",
        description="Primary brand color in hex format",
    )
    footer_text: str = Field(
        default="Generated by SEOman",
        max_length=100,
        description="Custom footer text",
    )


class ReportGenerateRequest(BaseModel):
    """Request to generate a report in a specific format."""

    format: str = Field(
        default="pdf",
        pattern=r"^(pdf|markdown)$",
        description="Output format: pdf or markdown",
    )
    options: PDFOptions = Field(
        default_factory=PDFOptions,
        description="PDF generation options",
    )


class ReportDownloadResponse(BaseModel):
    """Response containing report download URL."""

    url: str = Field(description="Presigned URL for downloading the report")
    filename: str = Field(description="Suggested filename for the download")
    expires_in: int = Field(description="URL expiration time in seconds")
    format: str = Field(description="Report format (pdf, markdown)")
